In [ ]:
import sympy as sp

def Submarine_body_added_mass(R, L, Rho):
    x, L1 = sp.symbols('x L1')

    # Surge direction added mass - m11 (using Prolate spheroid theory)
    L1 = L - 2 * R
    V = sp.pi * R**2 * (L1 + (4/3) * R)
    b = R
    a = (3 * V) / (4 * sp.pi * b**2)
    mdf = (4/3) * Rho * sp.pi * a * b**2 # given in lecture notes page 117
    e = sp.sqrt(1 - (b**2 / a**2))
    a0 = 2 * ((1 - e**2) / e**3) * ((0.5 * sp.log((1 + e) / (1 - e))) - e)
    k1 = a0 / (2 - a0)
    m11 = k1 * mdf

    # Other added masses (using Slender Body theory)
    a22 = Rho * sp.pi * R**2
    a33 = a22
    a44 = 0
    a55 = a33
    a66 = a22

    # Integration coefficients
    I1 = 1 - (((x + L1/2)**2) / R**2)
    I2 = 1                                    #(x/x)
    I3 = 1 - (((x - L1/2)**2) / R**2)

    q1 = sp.integrate(I1, (x, -(L1/2)-R, -L1/2))
    q2 = sp.integrate(I2, (x, -L1/2, L1/2))
    q3 = sp.integrate(I3, (x, L1/2, (L1/2) + R))

    m22 = a22 * (q1 + q2 + q3)

    m33 = a33 * (q1 + q2 + q3)

    m44 = a44 * (q1 + q2 + q3)

    I4 = x**2 * (1 - (((x + L1/2)**2) / R**2))
    I5 = x**2
    I6 = x**2 * (1 - (((x - L1/2)**2) / R**2))

    q4 = sp.integrate(I4, (x, -(L1/2)-R, -L1/2))
    q5 = sp.integrate(I5, (x, -L1/2, L1/2))
    q6 = sp.integrate(I6, (x, L1/2, (L1/2) + R))

    m55 = a55 * (q4 + q5 + q6)

    m66 = a66 * (q4 + q5 + q6)

    # Added mass matrix
    M_SB = sp.Matrix([[m11, 0, 0, 0, 0, 0],
                        [0, m22, 0, 0, 0, 0],
                        [0, 0, m33, 0, 0, 0],
                        [0, 0, 0, m44, 0, 0],
                        [0, 0, 0, 0, m55, 0],
                        [0, 0, 0, 0, 0, m66]])

    return M_SB.evalf()

Submarine_body_added_mass(0.115, 1.6, 1000)





Matrix([
[1.32397053517154,                0,                0, 0,                0,                0],
[               0, 63.2907873986078,                0, 0,                0,                0],
[               0,                0, 63.2907873986078, 0,                0,                0],
[               0,                0,                0, 0,                0,                0],
[               0,                0,                0, 0, 12.2852795287789,                0],
[               0,                0,                0, 0,                0, 12.2852795287789]])

In [ ]:
import sympy as sp

def Thruster_added_mass(R, L, W, Rho):
    x = sp.symbols('x')

    # Surge direction added mass - m11 (using Prolate spheroid theory) as shape is resumbling with spheriod
    L1 = L - 2 * R  # length of a cylinder
    V = sp.pi * R**2 * (L1 + (4/3) * R)  # Volume of the entire submarine body

    # Prolate spheroid parameters
    b = R  # Smaller axis length
    a = (3 * V) / (4 * sp.pi * b**2)  # Longer axis length
    mdf = (4/3) * Rho * sp.pi * a * b**2  # Mass of displaced fluid

    e = sp.sqrt(1 - (b**2 / a**2))  # Eccentricity
    a0 = 2 * ((1 - e**2) / e**3) * ((0.5 * sp.log((1 + e) / (1 - e))) - e)  # alpha0 coefficient

    # K-coefficient
    k1 = a0 / (2 - a0)

    # Added mass m11
    m11 = k1 * mdf

    # Other added masses (using Slender Body theory)
    a22 = 0 # this we already calculated in submarine body above its efect is negligible comapred to submarine value
    a33 = Rho * sp.pi * (L1/2)**2 #
    a44 = Rho * sp.pi * (W/2)**2
    a55 = a33
    a66 = 0 # same as a22

    # Added mass m22
    m22 = a22

    # Added mass m33
    I1 = x / x
    q1 = sp.integrate(I1, (x, -W/2, W/2))
    m33 = a33 * q1

    # Added mass m44
    I2 = x**2
    q2 = sp.integrate(I2, (x, -L1/2, L1/2))
    m44 = a44 * q2

    # Added mass m55
    Ir3 = x**2
    q3 = sp.integrate(Ir3, (x, -W/2, W/2))
    m55 = a55 * q3

    # Added mass m66
    m66 = a66

    # Added mass matrix
    M_T = sp.zeros(6)
    M_T= sp.Matrix([[m11, 0, 0, 0, 0, 0],
                        [0, m22, 0, 0, 0, 0],
                        [0, 0, m33, 0, 0, 0],
                        [0, 0, 0, m44, 0, 0],
                        [0, 0, 0, 0, m55, 0],
                        [0, 0, 0, 0, 0, m66]])

    return M_T.evalf()
Thruster_added_mass(0.045, 0.285, 0.0908, 1000)

# Lth = 0.285  # Approximate length of the thruster assembly
# Rth = 0.045 # Approximate radius of the thruster assembly
# Wth = 0.098 # Approximate width of the thruster assembly
# Rho = 1000

Matrix([
[0.121331092352793, 0,                0,                   0,                   0, 0],
[                0, 0,                0,                   0,                   0, 0],
[                0, 0, 2.71172067681747,                   0,                   0, 0],
[                0, 0,                0, 0.00400114385864417,                   0, 0],
[                0, 0,                0,                   0, 0.00186309673007636, 0],
[                0, 0,                0,                   0,                   0, 0]])

In [ ]:
import sympy as sp

def Antenna_added_mass(W_A, H_A, T_A, Rho=1000):
    x = sp.symbols('x')

    # Integration coefficients
    a11 = 1.7 * sp.pi * Rho * (T_A/2)**2  # ratio of T_A/W_A ~ 2
    a22 = 1.36 * sp.pi * Rho * (W_A/2)**2  # ratio of W_A/T_A ~ 0.5
    a33 = 0.19 * sp.pi * Rho * W_A * T_A
    a44 = a22
    a55 = a11
    a66 = 0.15 * sp.pi * Rho * (W_A/2)**4

    # Added mass m11
    I1 = x / x
    q1 = sp.integrate(I1, (x, -H_A/2, H_A/2))
    m11 = a11 * q1

    # Added mass m22
    m22 = a22 * q1

    # Added mass m33
    I3 = x / x  # Check if this is the correct shape function for integration
    q3 = sp.integrate(I3, (x, -H_A/2, H_A/2))
    m33 = a33 * q3

    # Added mass m44
    I2 = x**2
    q2 = sp.integrate(I2, (x, -H_A/2, H_A/2))
    m44 = a44 * q2

    # Added mass m55
    m55 = a55 * q2

    # Computing m66
    m66 = a66 * q1

    # Added mass matrix
    M_ANT = sp.zeros(6)
    M_ANT = sp.Matrix([[m11, 0, 0, 0, 0, 0],
                       [0, m22, 0, 0, 0, 0],
                       [0, 0, m33, 0, 0, 0],
                       [0, 0, 0, m44, 0, 0],
                       [0, 0, 0, 0, m55, 0],
                       [0, 0, 0, 0, 0, m66]])

    return M_ANT.evalf()

Antenna_added_mass(0.069, 0.26, 0.0355)


Matrix([
[0.437490731656362,                0,                 0,                   0,                   0,                   0],
[                0, 1.32220963993871,                 0,                   0,                   0,                   0],
[                0,                0, 0.380149361525429,                   0,                   0,                   0],
[                0,                0,                 0, 0.00744844763832137,                   0,                   0],
[                0,                0,                 0,                   0, 0.00246453112166417,                   0],
[                0,                0,                 0,                   0,                   0, 0.00017357647322835]])

In [ ]:
# Here we will move our matrics from their CG to CG of sparus

import numpy as np

def S_(rg): # distance vector from CG_ind to CG_ sparus
    vector_Skew_M = np.array([[0, -rg[2], rg[1]],
                              [rg[2], 0, -rg[0]],
                              [-rg[1], rg[0], 0]])
    return vector_Skew_M

def Move_to_CG(r, M): # transfer to CG_sparus
    OO = np.zeros((3, 3))  # 3x3 matrix of zeros
    Id = np.eye(3)  # 3x3 identity matrix

    H = np.block([[Id, S_(r).T], [OO, Id]]) # rotation matrics
    HT = H.T  # Transpose of matrix

    M_CG = np.dot(np.dot(HT, M), H)

    return M_CG




In [ ]:
import numpy as np

def S_(rg):
    vector_Skew_M = np.array([[0, -rg[2], rg[1]],
                              [rg[2], 0, -rg[0]],
                              [-rg[1], rg[0], 0]])
    return vector_Skew_M

def Move_to_CG(r, M):
    OO = np.zeros((3, 3))
    Id = np.eye(3)

    H = np.block([[Id, S_(r).T], [OO, Id]])
    HT = H.T

    M_CG = np.dot(np.dot(HT, M), H)

    return M_CG

# Input values
L = 1.6   # Total length of the submarine
R = 0.115 # Radius of the submarine
m = 52   # Submarine mass

W3 = 0.066  # Width of the Antenna
H3 = 0.255   # Height of the Antenna
T3 = 0.03   # Thickness of the Antenna

Lth = 0.285  # Approximate length of the thruster assembly
Rth = 0.045 # Approximate radius of the thruster assembly
Wth = 0.098 # Approximate width of the thruster assembly
Rho = 1000

# Distance vectors
rg_SB = np.array([0.0555, 0, 0])
rg_ANT = np.array([-0.412, 0, -0.2425])

rg_RT = np.array([-0.532, 0.148, 0])
rg_LT = np.array([-0.532, -0.148, 0])

# Calculate added mass matrices
Mb_SB = Submarine_body_added_mass(R, L, Rho)
Mg_SB = Move_to_CG(rg_SB, Mb_SB)
print("Added Mass Matrix - Submarine Body:")
print(Mg_SB)

Mb_TL = Thruster_added_mass(Rth, Lth, Wth, Rho)
Mg_TL = Move_to_CG(rg_LT, Mb_TL)
print("Added Mass Matrix - Thruster Left:")
print(Mg_TL)

Mb_TR = Thruster_added_mass(Rth, Lth, Wth, Rho)
Mg_TR = Move_to_CG(rg_RT, Mb_TR)
print("Added Mass Matrix - Thruster Right:")
print(Mg_TR)

Mb_ANT = Antenna_added_mass(W3, H3, T3, Rho)

Mg_ANT = Move_to_CG(rg_ANT, Mb_ANT)
print("Added Mass Matrix - Antenna:")
#############x
print(Mg_ANT)
# we will all added mass matrics of thrusters
Mg_Thruster= Mg_TL + Mg_TR
print("Added Mass Matrix - Thruster:")
print(Mg_Thruster)
#Added mass matrics of all sub bodies
MCG = Mg_Thruster + Mg_ANT + Mg_SB
print("Added mass Matrics at the centre of gravity is:" , MCG)

Added Mass Matrix - Submarine Body:
[[1.32397053517154 0 0 0 0 0]
 [0 63.2907873986078 0 0 0 3.51263870062273]
 [0 0 63.2907873986078 0 -3.51263870062273 0]
 [0 0 0 0 0 0]
 [0 0 -3.51263870062273 0 12.4802309766634 0]
 [0 3.51263870062273 0 0 0 12.4802309766634]]
Added Mass Matrix - Thruster Left:
[[0.121331092352793 0 0 0 0 0.0179570016682133]
 [0 0 0 0 0 0]
 [0 0 2.92674698599242 -0.433158553926878 1.55702939654797 0]
 [0 0 -0.433158553926878 0.0687683105563709 -0.230440350689099 0]
 [0 0 1.55702939654797 -0.230440350689099 0.830682012134642 0]
 [0.0179570016682133 0 0 0 0 0.00265763624689557]]
Added Mass Matrix - Thruster Right:
[[0.121331092352793 0 0 0 0 -0.0179570016682133]
 [0 0 0 0 0 0]
 [0 0 2.92674698599242 0.433158553926878 1.55702939654797 0]
 [0 0 0.433158553926878 0.0687683105563709 0.230440350689099 0]
 [0 0 1.55702939654797 0.230440350689099 0.830682012134642 0]
 [-0.0179570016682133 0 0 0 0 0.00265763624689557]]
Added Mass Matrix - Antenna:
[[0.306423093449514 0 0 0 -0

In [ ]:
# From CG of Sparus we can move it to Centre of bouynacy by calling the function Move to CB

def S_(rb):
    vector_Skew_M = np.array([[0, -rb[2], rb[1]],
                              [rb[2], 0, -rb[0]],
                              [-rb[1], rb[0], 0]])
    return vector_Skew_M

def Move_to_CB(rb, M):
    OO = np.zeros((3, 3))
    Id = np.eye(3)

    H = np.block([[Id, S_(rb).T], [OO, Id]])
    HT = H.T

    M_CB = np.dot(np.dot(HT, M), H)

    return M_CB
rb=np.array([0,0,-0.02])
M_bouyancy = Move_to_CB(rb, MCG)
print(M_bouyancy)


[[1.87305581332664 0 0 0 -0.111768716428040 0]
 [0 64.4772576164443 0 1.57726418015424 0 3.02381297087409]
 [0 0 69.4456574954442 0 -0.274412944087971 0]
 [0 1.57726418015424 0 0.251037335012884 0 -0.0580639800465650]
 [-0.111768716428040 0 -0.274412944087971 0 14.2161533393781 0]
 [0 3.02381297087409 0 -0.0580639800465650 0 12.6870849571005]]


Drag Matrics

In [ ]:
import numpy as np
from sympy import pi

# Constants
Re = 100000  # Reynolds number for turbulent flow
V = 1  # velocity, arbitrary
Rho = 1000  # density
L = 1.6  # total length of the submarine
R = 0.115  # radius of the submarine

Cd_long_x = 0.1125  # because L/2R ~ 7, it has to be between 0.1 and 0.15
Cd_lateral_y = 0.8  # because cylindrical rod.
Cd_Z = Cd_lateral_y  # because of symmetry

# Initialize the zeros matrix
K_cd = np.zeros((6, 6))

# To calculate the drag coefficients, we use two things: the projected surfaces for K11, K22, and K33;
# and the coefficients of drag, as well as the friction coefficient
Sx = pi * R**2  # symbols are same as per the provided document

K_cd[0, 0] = 0.5 * Rho * Sx * Cd_long_x
K_cd[1, 1] = 0.5 * Rho * L * R * Cd_lateral_y
K_cd[2, 2] = 0.5 * Rho * L * R * Cd_Z  # same as in y because of symmetry
K_cd[3, 3] =  0 # 1/64*Rho*R**4*L*Cd_long_x
K_cd[4, 4] = 1/64 * Rho * L**4 * R * Cd_Z
K_cd[5, 5] = K_cd[4, 4]  # symmetry
# K_Cd =-K_cd
print(K_cd)



[[ 2.33705041  0.          0.          0.          0.          0.        ]
 [ 0.         73.6         0.          0.          0.          0.        ]
 [ 0.          0.         73.6         0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          9.4208      0.        ]
 [ 0.          0.          0.          0.          0.          9.4208    ]]


In [ ]:
import numpy as np
from sympy import pi

# Constants for Antenna
W_A = 0.03  # Width of the Antenna
H_A = 0.255  # Height of the Antenna
T_A = 0.065 # Thickness of the Antenna

Cd_surge = 2 # because T_A/H_A ~ 0.2165 close to 0.1
Cd_sway = 1.9  # because W_A/H_A ~ 0.117 close to 0.1
Cd_heave = 2.5  # because W_A/T_A ~ 0.46 close to 0.5

rho = 1000  # density

# Initialize an empty K matrix
K_cd_A = np.zeros((6, 6))

# Surface areas
Surf_1 = H_A * W_A
Surf_2=  H_A * T_A
Surf_3 = W_A * T_A

# To calculate the drag coefficients, we use two things: the projected surfaces for K11, K22, and K33;
# and the coefficients of drag, as well as the friction coefficient
Sx = pi * R**2  # symb
# Calculate the drag coefficients
K_cd_A[0, 0] = 0.5 * rho * Surf_1* Cd_surge
K_cd_A[1, 1] = 0.5 * rho * Surf_2* Cd_sway
K_cd_A[2, 2] = 0.5 * rho * Surf_3* Cd_heave
K_cd_A[3, 3] =0
K_cd_A[4, 4] =1/64*Cd_sway*H_A**4*T_A
K_cd_A[5, 5] =1/64*Cd_sway*H_A**4*W_A
# Display the K_antenna matrix

print("K_Cd_Antenna:")
print(K_cd_A)


K_Cd_Antenna:
[[7.65000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.57462500e+01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.43750000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  8.15920238e-06 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 3.76578571e-06]]


In [ ]:
1.57462500e+01

15.74625

In [ ]:
import numpy as np
from sympy import  pi

# Constants for thruster 1 and thruster 2
L_T = 0.285  # Approximate length of the thruster assembly
R_T = 0.046  # Approximate radius of the thruster assembly


Rho = 1000  # density


# thruster 1
Cd_surge_T1 = 0.7  # because L_T/2R_T =3.09
Cd_sway_T1 = 1.9  # because plate 2R_T/L_T=0.16
Cd_heave_T1 = 1.9  # because plate

# Surface areas
Surf_surge = pi * R_T**2
Surf_sway = 2 * R_T * L_T
Surf_heave = 2*R_T* L_T

# Initialize an empty
# To calculate the drag coefficients, we use two things: the projected surfaces for K11, K22, and K33;
# and the coefficients of drag, as well as the friction coefficient
Sx = pi * R**2  # symbK matrix for thruster 1
K_T1 = np.zeros((6, 6))

# Calculate the drag coefficients
K_T1[0, 0] = 0.5 * Rho * Surf_surge * Cd_surge_T1
K_T1[1, 1] = 0.5 * Rho * Surf_sway * Cd_sway_T1
K_T1[2, 2] = 0.5 * Rho * Surf_heave * Cd_heave_T1
K_T1[3, 3] = 0
K_T1[4, 4] = 1/64*Rho*Surf_heave*L_T**3
K_T1[5, 5] = 1/64*Rho*Surf_heave*L_T**3
# Display the K_M1 matrix
K_T1=-K_T1
print("K_T1:")
print(K_T1)

# thruster 2
K_T2 = K_T1 # it isa same for thurster two as they are same dimensions

# Display the K_M2 matrix
print("\nK_T2:")
print(K_T2)


K_T1:
[[-2.32666352e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -2.49090000e+01 -0.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -2.49090000e+01 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  -9.48390715e-03 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -9.48390715e-03]]

K_T2:
[[-2.32666352e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -2.49090000e+01 -0.00000000e+00 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -2.49090000e+01 -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  -0.000000

Mapping of Thrusters as we have three thrusters one is above the center of gravity of the submarine and two on the sides of the center of gravity of the submarine


# Matrix Equation

# Matrix Multiplication

Let \( Eb \) be the 3x3 matrix:

\[
Eb = \begin{bmatrix}
0 & 1 & 1 \\
0 & 0 & 0 \\
1 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & -0.17 & 0.17
\end{bmatrix}
\]

And let \( \mathbf{F} \) be the 3x1 column vector:

\[
\mathbf{F} = \begin{bmatrix}
F_1 \\
F_2 \\
F_3 \\
\end{bmatrix}
\]

The result of the matrix multiplication \( A \times \mathbf{F} \) is a 3x1 column vector:

\[
\begin{bmatrix}
0 \cdot F_1 + 1 \cdot F_2 + 1 \cdot F_3 \\
0 \cdot F_1 + 0 \cdot F_2 + 0 \cdot F_3 \\
1 \cdot F_1 + 0 \cdot F_2 + 0 \cdot F_3 \\
0 \cdot F_1 + 0 \cdot F_2 + 0 \cdot F_3 \\
0 \cdot F_1 + 0 \cdot F_2 + 0 \cdot F_3 \\
0 \cdot F_1 + -0.17 \cdot F_2 + 0.17 \cdot F_3 \\
\end{bmatrix}
\]

This represents the result of multiplying matrix \( A \) by vector \( \mathbf{F} \).

so, we a have the  thrusters forces and moments  repers etd in the above equation with repectiver forcers and moments created by three thrusters along the diffents axes of the submarine

Move to center of grvaity

In [ ]:
import numpy as np

def drag_force_to_gravity_center(r, F):

    Zero_mat = np.zeros((3, 3))
    Id_mat = np.eye(3)

    S_r = np.array([[0, -r[2], r[1]],
                    [r[2], 0, -r[0]],
                    [-r[1], r[0], 0]])

    H = np.block([[Id_mat, S_r.T],
                  [Zero_mat, Id_mat]])

    HT = H.T

    Fg = np.dot(HT, F)

    return Fg


Here i tried to use K factor theory but bo is becoming infinity , i will use slender theory wuth the assumption of L/D>>10

In [ ]:
import sympy as sp

def Thruster_added_mass(R, L, W, rho):
    x = sp.symbols('x')

    # Surge direction added mass - m11 (using Prolate spheroid theory) as shape is resumbling with spheriod
    L1 = L - 2 * R  # length of a cylinder
    V = sp.pi * R**2 * (L1 + (4/3) * R)  # Volume of the entire submarine body

    # Prolate spheroid parameters
    b = R  # Smaller axis length
    a = (3 * V) / (4 * sp.pi * b**2)  # Longer axis length
    mdf = (4/3) * rho * sp.pi * a * b**2  # Mass of displaced fluid

    e = sp.sqrt(1 - (b**2 / a**2))  # Eccentricity
    a0 = 2 * ((1 - e**2) / e**3) * ((0.5 * sp.log((1 + e) / (1 - e))) - e)  # alpha0 coefficient
    b0=((1/e**2)- (1-e**2))/(2*(e**3)*sp.log((1+e)/1-e))
    # K-coefficient
    k1 = a0 / (2 - a0)
    print(k1)
    k2=b0/2-b0
    print(k2)
    k3=k2
    k4=0
    k5=(e**4*(b0-a0))/((2-e**2)*(2*e**2-(2-e**2)*(b0-a0)))
    print(k5)
    k6=k5
    # Added mass m11
    m11 = k1 * mdf
    m22=k2*mdf
    m33=k3*mdf
    m44=k4*mdf
    m55=k5*mdf
    m66=k6*mdf
     # Added mass matrix
    M_T = sp.zeros(6)
    M_T= sp.Matrix([[m11, 0, 0, 0, 0, 0],
                        [0, m22, 0, 0, 0, 0],
                        [0, 0, m33, 0, 0, 0],
                        [0, 0, 0, m44, 0, 0],
                        [0, 0, 0, 0, m55, 0],
                        [0, 0, 0, 0, 0, m66]])

    return M_T.evalf()
Thruster_added_mass(0.045, 0.261, 0.106, 1000)



0.0861061223880023
nan
nan


Matrix([
[0.126537984361539,   0,   0, 0,   0,   0],
[                0, nan,   0, 0,   0,   0],
[                0,   0, nan, 0,   0,   0],
[                0,   0,   0, 0,   0,   0],
[                0,   0,   0, 0, nan,   0],
[                0,   0,   0, 0,   0, nan]])

In [ ]:
#(e**4*(b0-a0))/((2-e**2)*(2*e**2-(2-e**2)*(b0-a0)))
L=1.6
R=0.115
L1 = L - 2 * R  # length of a cylinder
V = sp.pi * R**2 * (L1 + (4/3) * R)  # Volume of the entire submarine body

# Prolate spheroid parameters
b = R  # Smaller axis length
a = (3 * V) / (4 * sp.pi * b**2)
e = sp.sqrt(1 - (b**2 / a**2))  # Eccentricity
a0 = 2 * ((1 - e**2) / e**3) * ((0.5 * sp.log((1 + e) / (1 - e))) - e)  # alpha0 coefficient
b0=(1/e**2- (1-e**2))/(2*(e**3)*sp.log((1+e)/1-e))
a0
b0

zoo